# fly.toml app configuration file generated for screen-recorder on 2023-09-30T21:41:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "screen-recorder"
primary_region = "atl"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
